### PR TITLE
a handful of smaller changes

### PR DESCRIPTION
**Pull request by dgoodare**
- Created the shopping-list page
- Updated the other pages to include the link to the shopping-list page

I'm not sure what's actually going on this page so if you guys could explain what this page is supposed to have, I'll get working on it as soon as I can

### CODE REVIEW

**Comment by dgoodare** [comment]
I also tried to put the JavaScript for the contact page (the mapbox stuff) into a separate file as well but it broke the map so it might be best to leave it where it is for now

**Comment by JFergus98** [comment]
the shopping list page is supposed to be similar to the ToDo TaDa webpage we made in a lab a few weeks back. But instead of a to do list it will be a shopping list where you can add and remove items from the list. Also i think certain things like the map API might need javascript on the page and not in a separate file but i am not sure

**Comment by dgoodare** [comment]
I couldn't get that lab exercise working when i first tried it, but I'll have another crack at it and see if I can get it working with the rest of the website

**Comment by LewisMoore19** [comment]
Its seem to me that shop.html is behind a version compared to the dev branch one (the JS at the bottom) or was it moved to another file?

**Comment by dgoodare** [comment]
the JS is another file but there are other JS files that are in other folders, so we'll need to decide which one they are all going to go in

**Comment by cameron14** [comment]
If I merge this pull request will it break anything, such as the shopping list page thats already on the development branch???

**Comment by dgoodare** [comment]
I've deleted that version of the shopping-list so it shouldn't, but I've just noticed that the shop.js file has the wrong file path, so I'll remove that and it should be fine to merge

**Pull request merged**
