### PR TITLE
Made a lot of little changes

### PR DESCRIPTION
**Pull request by JFergus98**
Updated navbars on each page
moved master css file to a css folder
updated the shop buttons with categories from the little green larder
moved css from shop.html to master.css
added logo source to each page it was missing on
added alt descriptions to logos on each page
add i fixed a few errors i made along the way

### CODE REVIEW

**Comment by LewisMoore19** [comment]
Changes are good.
I made a home page called home.html
Shop.html will need its linked changed instead of index

**Comment by JFergus98** [comment]
I thought the home page had to be called index.html for the Github website to work?

**Comment by cameron14** [comment]
Yeah that’s right about the index.html, Jamie.

**Comment by LewisMoore19** [comment]
Me and Cameron got together and fixed some issues with the pull request and the development folder, your files were pushed using another pull request.

**Comment by JFergus98** [comment]
I don't understand, why not just merge this, or make the changes on this branch?

**Comment by LewisMoore19** [comment]
Couldn't merge yours, due to file/compatibility errors.
Didn't want to touch your branch.
Implemented fixes.
Two birds with one stone approach

**Comment by JFergus98** [comment]
but all the commits i have made are now are not going to be implemented and the branch is now dead, and you can resolve conflicts

**Comment by LewisMoore19** [comment]
Im sure you can add a note if you want, the pull request is called "fixed version of Jamies" and this pull request had been documented, No one can dispute it and you have valid proof.  

We couldn't resolve the conflicts, we tried. It wanted you to do it so we just moved on

**Pull request closed without merging**
