### PR TITLE
final changes to shop

### PR DESCRIPTION
**Pull request by JFergus98**
add the stock images, looks a bit clunky since they are sometimes different sizes but i don't really have time to fix it. I also tried to add a button to add products from the shop to the shopping list but i could not get it working so i removed it. I think i also fixed the manifest.

### CODE REVIEW

**Comment by JFergus98** [comment]
also i moved the javascript for the shop to a separate file

**Comment by dgoodare** [comment]
the shop.html seems to be missing the link to the external page

**Comment by JFergus98** [comment]
I quickly added it, i am not sure why i am getting conflicts

**Comment by ivanamigo27** [comment]
Should we merge now?

**Comment by dgoodare** [comment]
You had it title as Contact, but I fixed it

**Comment by cameron14** [comment]
This looks great!

**Pull request merged**
