### PR TITLE
created a basic homepage template

### PR DESCRIPTION
**Pull request by JFergus98**
I have created a basic homepage with navigation bar, main section and footer.

The navbar contains a placeholder image for the logo and placeholder names for the title of the web page and the links to each page(page 2, page 3, etc).

The main section just has some lorem ipsum in it to fill it up at the moment.

The footer contains our names plus Dundee uni.

Also contains the bootstrap JavaScript which will need to be moved to its separate file at a later date.

### CODE REVIEW

**Comment by cameron14** [comment]
I ran it through W3 HTML validator and it said there is a stray closing span tag on line 63. Is that a mistake or is it supposed to be there?

**Comment by JFergus98** [comment]
probably a mistake
________________________________

**Comment by JFergus98** [comment]
just fixed it

________________________________

**Comment by cameron14** [comment]
It looks pretty decent, I like the nav bar!

**Pull request merged**
